version: "3.7"

services:
  anniv.lgna.fr:
    image: gaspardcothiasfaure/anniv.lgna.fr:0.1
    container_name: anniv.lgna.fr
    restart: always
    volumes:
      - "/home/debian/lgna-sandbox/anniv.lgna.fr/output.txt:/app/output.txt"
